### ISSUE TITLE
CRITCAL: Bilar kan lastas av medan CarTransporter rör på sig.

### ISSUE THREAD

**Issue by WilliamFrisk** [Heldereim/TDA553-lab1#10]
https://github.com/Heldereim/TDA553-lab1/blob/93ef1b5504300f9c7f9701d213909d62e991b1fb/Trucks/CarTransporter.java#L25-L27

Koden ovan tillåter att bilar lastas av medan CarTransporter rör på sig. Gör något liknande som i er load metod istället :)

**Comment by Heldereim** [comment]
Vi antog att det räckte att pop metoden för Stack kastar ett felmeddelande om stacken är tom. Vi kommenterade koden för att göra det lite tydligare.

Menar du att vi ska göra ett eget kast av Exception?

**Comment by WilliamFrisk** [comment]
Stacken kastar ett felmeddelande om den är tom men inte om cartransporter rör på sig eller hur? Stacken har ingen koll på CarTransporters fart och bör inte ha det heller. Men jag ser att ni löst det, snyggt👍🏻
