### ISSUE TITLE
CRITICAL Labb 2: Kan lasta på och av bilar trots att flaket är uppe

### ISSUE THREAD

**Issue by WilliamFrisk** [Heldereim/TDA553-lab1#14]
https://github.com/Heldereim/TDA553-lab1/blob/7f88d25200a11ffd50800d56834b560db2065b15/src/Model/CarTransporter.java#L16-L25

Ni har tagit bort er check för att kolla om flaket är i rätt position. Den är viktig eftersom man bara ska kunna lasta på bilar när flaket är nere. Se till att checken finns i båda metoderna :)

**Comment by kalimooo** [comment]
Fixat i senaste uppdatering Lab3b
