### ISSUE TITLE
Använder setters innanför klassen

### ISSUE THREAD

**Issue by WilliamFrisk** [Heldereim/TDA553-lab1#5]
Koden nedan använder en setter som finns i samma klass. Konventionen är att direkt ge instansattributet ett värde istället för att gå igenom en setter. Då blir koden mer lättläslig.

https://github.com/Heldereim/TDA553-lab1/blob/853853b06e143661903015d138baff3b5c249868/Car.java#L88

**Comment by Heldereim** [comment]
Ändrade koden till 
this.currentSpeed = (Math.min(getCurrentSpeed() + speedFactor() * amount, this.getEnginePower()));
istället
