### ISSUE TITLE
CRITICAL: Test fail

### ISSUE THREAD

**Issue by WilliamFrisk** [Heldereim/TDA553-lab1#8]
https://github.com/Heldereim/TDA553-lab1/blob/93ef1b5504300f9c7f9701d213909d62e991b1fb/Tests/ScaniaTest.java#L39

Raden ovan förväntar sig att scania kastar ett IllegalArgumentException men scania kastar ett IllegalStateException så testet failar.

**Comment by Heldereim** [comment]
Löst nu, vi insåg att IllegalArgumentException var fel sorts exception för den metoden och glömde ändra i testerna.
